- name: Demo on Play Level Variable
  hosts: all
  vars:
    URL: Play.example.com
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL - {{ URL }}


- name: Load vars from a file
  hosts: all
  vars_files:
    - exvars.yml

  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL - {{ URL }}





- name: Demo on Task Level Variables
  hosts: all
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL - {{ URL }}
      vars:
        URL: tasks.example.com




- name: Variable from Roles
  hosts: all
  vars:
    URL_PLAY: play.example.com
  roles:
    - sample


- name: Demo on register variables
  hosts: all
  tasks:
    - name: Run Uptime shell command
      ansible.builtin.shell: uptime
      register: output
    - name: Print output
      ansible.builtin.debug:
        msg: "{{ output.stdout }}"

