- name: Print a parameter
  hosts: local host
  connection: local
  tasks:
    -name: print a parameter
    ansible.builtin.debug:
      msg: Parameter - {{ lookup('aws_ssm', 'test.test1', region='us-east-1' ) }}